In [1]:
import pandas as pd

In [11]:
df=pd.read_csv('../data/raw_stock_data.csv')
df.head(20)

          Date      Close       High        Low       Open     Volume Stock
0   2020-01-02  72.333885  72.394093  71.091191  71.344062  135480400  AAPL
1   2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800  AAPL
2   2020-01-06  72.201416  72.239950  70.503554  70.754021  118387200  AAPL
3   2020-01-07  71.861832  72.466315  71.642674  72.211033  108872000  AAPL
4   2020-01-08  73.017853  73.318893  71.565636  71.565636  132079200  AAPL
5   2020-01-09  74.568794  74.761457  73.742742  73.993202  170108400  AAPL
6   2020-01-10  74.737381  75.300934  74.236454  74.802410  140644800  AAPL
7   2020-01-13  76.334099  76.360594  74.934866  75.052878  121532000  AAPL
8   2020-01-14  75.303329  76.481001  75.180510  76.271479  161954400  AAPL
9   2020-01-15  74.980629  75.982491  74.549538  75.103456  121923600  AAPL
10  2020-01-16  75.919868  76.030656  75.161249  75.522497  108829200  AAPL
11  2020-01-17  76.760368  76.762772  75.862063  76.167916  137816400  AAPL
12  2020-01-21  76.240173  76.830207  76.102897  76.389488  110843200  AAPL
13  2020-01-22  76.512306  77.063806  76.418378  76.724232  101832400  AAPL
14  2020-01-23  76.880768  76.960239  76.018586  76.565279  104472000  AAPL
15  2020-01-24  76.659225  77.868199  76.468966  77.126440  146537600  AAPL
16  2020-01-27  74.405045  75.084185  73.424857  74.672365  161940000  AAPL
17  2020-01-28  76.509903  76.680892  75.185327  75.284069  162234000  AAPL
18  2020-01-29  78.111427  78.956750  77.398567  78.137923  216229200  AAPL
19  2020-01-30  77.998238  78.051221  76.765179  77.196271  126743200  AAPL

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7548 entries, 0 to 7547
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    7548 non-null   str
 1   Close   7548 non-null   float64
 2   High    7548 non-null   float64
 3   Low     7548 non-null   float64
 4   Open    7548 non-null   float64
 5   Volume  7548 non-null   int64
 6   Stock   7548 non-null   str
dtypes: float64(4), int64(1), str(2)
memory usage: 412.9 KB

In [13]:
df.shape

(7548, 7)

In [14]:
df.describe()

             Close         High          Low         Open        Volume
count  7548.000000  7548.000000  7548.000000  7548.000000  7.548000e+03
mean    158.969793   161.129713   156.673426   158.933919  1.321826e+08
std      95.080975    96.260754    93.842097    95.114233  1.691460e+08
min       4.890825     5.228001     4.499358     4.982962  7.164500e+06
25%      98.539082    99.987833    96.579278    98.176358  3.349680e+07
50%     149.385643   151.556374   147.203844   149.302074  6.457850e+07
75%     209.220005   213.366569   205.851814   209.402496  1.321587e+08
max     479.859985   488.540009   457.510010   475.899994  1.543911e+09

In [15]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Stock'], dtype='str')

In [ ]:
# Convert date
df['Date']=pd.to_datetime(df['Date'])
print(df['Date'].dtype)

datetime64[us]

In [ ]:
#  checking null values
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
Stock     0
dtype: int64

In [ ]:
# Checking duplicate values
df.duplicated().sum()

np.int64(0)

In [20]:
# Chceking if there is any negative price of stock 
(df[['Open','High','Low','Close']] < 0).sum()

Open     0
High     0
Low      0
Close    0
dtype: int64

In [21]:
#  Validating volume 
(df['Volume'] < 0).sum()

np.int64(0)

In [22]:
# Checking OHLC Consistency 
df = df[
    (df['High']>=df['Open']) &
    (df['High']>=df['Close']) &
    (df['Low']<=df['Open']) &
    (df['Low']<=df['Close'])
]

In [23]:
# adding date feature

df['Year'] = df['Date'].dt.year

df['Month'] = df['Date'].dt.month

df['Quarter'] = df['Date'].dt.quarter

df['Day'] = df['Date'].dt.day

In [24]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Stock', 'Year',
       'Month', 'Quarter', 'Day'],
      dtype='str')

In [25]:
df.head()

,Date,Close,High,Low,Open,Volume,Stock,Year,Month,Quarter,Day
0,2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,AAPL,2020,1,1,2
1,2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,AAPL,2020,1,1,3
2,2020-01-06,72.201416,72.239950,70.503554,70.754021,118387200,AAPL,2020,1,1,6
3,2020-01-07,71.861832,72.466315,71.642674,72.211033,108872000,AAPL,2020,1,1,7
4,2020-01-08,73.017853,73.318893,71.565636,71.565636,132079200,AAPL,2020,1,1,8

In [28]:
df.to_csv(
    "../data/cleaned_stock_data.csv",
    index=False
)

print("Saved successfully")

Saved successfully

In [30]:
clean = pd.read_csv("../data/cleaned_stock_data.csv")
df.columns
df.head()

,Date,Close,High,Low,Open,Volume,Stock,Year,Month,Quarter,Day
0,2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,AAPL,2020,1,1,2
1,2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,AAPL,2020,1,1,3
2,2020-01-06,72.201416,72.239950,70.503554,70.754021,118387200,AAPL,2020,1,1,6
3,2020-01-07,71.861832,72.466315,71.642674,72.211033,108872000,AAPL,2020,1,1,7
4,2020-01-08,73.017853,73.318893,71.565636,71.565636,132079200,AAPL,2020,1,1,8